// Each new term in the Fibonacci sequence is generated by
// adding the previous two terms. By starting with 1 and 2,
// the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose
// values do not exceed four million, find the sum of the even-valued terms.

var num = [1, 2, 3, 5, 8, 13, 21, 34, 55, 89];

// num.reduce(function(prev, curr, index, all){
//   console.log(prev, curr);
//   return prev + curr;
// });

function euler2(prev, curr){
  var sum = 0;
  for (curr = curr; curr < 4000000; curr = prev + curr){
    console.log('prev is ', prev, ' and curr is ',curr)
    prev = curr - prev;
    if (curr % 2 === 0){
      sum += curr;
    }
  }
  console.log("\nVictory, or Death!\n")
  return sum;
}

console.log(euler2(1, 2));
